### ISSUE TITLE
动态变量名

### ISSUE THREAD

**Issue by anzhizh** [juzstu/TianCheng#1]
您好，代码中的动态变量名部分是不是有问题呢？

**Comment by juzstu** [comment]
你好，你指的变量名是哪个？

**Comment by juzstu** [comment]
> 您好，代码中的动态变量名部分是不是有问题呢？
你好，你指的变量名是哪个？

**Comment by juzstu** [comment]
https://github.com/juzstu/TianCheng/issues/1#issue-391539705

> 
> 
> 您好，代码中的动态变量名部分是不是有问题呢？

你好，你指的变量名是哪些？

**Comment by anzhizh** [comment]
gen_stat_feat.py的第90行，其他类似的动态变量名部分也有问题

**Comment by anzhizh** [comment]
又或是我理解的有问题，请指教

**Comment by juzstu** [comment]
> 
> 
> 又或是我理解的有问题，请指教

data_tmp[f'uid_week_{wd}_cnt'] = data_frame[data_frame['nweek_day'] == wd].groupby('UID')['day'].count() 这里哪里你觉得有问题？

**Comment by anzhizh** [comment]
运行的时候，[f'uid_week_{wd}_cnt']这里直接报错，是不是我使用的问题

**Comment by juzstu** [comment]
> 
> 
> 运行的时候，[f'uid_week_{wd}_cnt']这里直接报错，是不是我使用的问题

f''是py3.6的新特性，你那边py的版本可能低于3.6

**Comment by anzhizh** [comment]
哦哦好的，多谢
